### PR TITLE
First attempt at a Python 3 version.

### PR DESCRIPTION
**Pull request by reutenauer**
This slightly modified version of `dviasm.py` works with Python 3; I haven’t tested it intensively yet.

I’ll make an attempt at a single file that works with both Python versions later.

### CODE REVIEW

**Comment by khaledhosny** [comment]
> I’ll make an attempt at a single file that works with both Python versions later.

A Python 3-only version is fine by me, Python 2 is nearly EOL.

**Comment by reutenauer** [comment]
True enough.  Let me test a bit more though, there’s no need to rush (I just reacted to Ulrike’s email on the TeX Live list).

**Comment by khaledhosny** [comment]
Let me know when you this this ready, and please overwrite the old file so the diff is visible on GitHub interface.

**Comment by norbusan** [comment]
Hi @reutenauer 
thanks for the changes, they look fine to me, but there are a few problems remaining:

- shebang should be python3
- crash 1: normal dvi file
```
  File "dviasm.py", line 1220, in <module>
    else:              aDVI.DumpToFile(sys.stdout, tabsize=options.tabsize, encoding=options.encoding)
  File "dviasm.py", line 941, in DumpToFile
    fp.write("set: %s\n" % PutStr(cmd[1]))
  File "dviasm.py", line 230, in PutStrUTF8
    else:               s += chr(o).encode('utf8')
TypeError: can only concatenate str (not "bytes") to str
```
- crash 2: ptex dvi file
```
  File "dviasm.py", line 1220, in <module>
    else:              aDVI.DumpToFile(sys.stdout, tabsize=options.tabsize, encoding=options.encoding)
  File "dviasm.py", line 941, in DumpToFile
    fp.write("set: %s\n" % PutStr(cmd[1]))
  File "dviasm.py", line 229, in PutStrUTF8
    s += ''.join(['\x1b$B', chr(o/256), chr(o%256)]).decode('iso2022-jp').encode('utf8')
TypeError: integer argument expected, got float
```

Best

**Comment by reutenauer** [comment]
Thanks @norbusan, I’ll have a look later today (European time).

**Comment by reutenauer** [comment]
I think I addressed all the problems reported by @norbusan, and rewrote `dviasm.py` as @khaledhosny asked.

**Comment by khaledhosny** [comment]
Thanks!

**Pull request merged**
